GUI:
  name: "&8[ &e&lCOIN&f&lLIP &8]"
  primary-color: "&e"

  help-head: "http://textures.minecraft.net/texture/797955462e4e576664499ac4a1c572f6143f19ad2d6194776198f8d136fdb2"
  middle: "http://textures.minecraft.net/texture/e825419e429afc040c9e68b10523b917d7b8087d63e7648b10807da8b768ee"
  arrow-left: "http://textures.minecraft.net/texture/b76230a0ac52af11e4bc84009c6890a4029472f3947b4f465b5b5722881aacc7"
  arrow-right: "http://textures.minecraft.net/texture/dbf8b6277cd36266283cb5a9e6943953c783e6ff7d6a2d59d15ad0697e91d43c"

Messages:
  ikkenokpenge: "&8[ &e&lCOIN&f&lFLIP &8] &cDu har ikke nok penge."
  flipertaget: "&8[ &e&lCOIN&f&lFLIP &8] &cDette flip er allerede taget"
  DuFjernedCoinflip: "&8[ &e&lCOIN&f&lFLIP &8] &aDu har fjernet dit coinflip"
  Duvandt: "&8[ &e&lCOIN&f&lFLIP &8] &aDu vandt coinflippet imod %random% og vandt &a&l%pris%"
  DuTabte: "&8[ &e&lCOIN&f&lFLIP &8] &cDu tabte coinflippet imod %vinder% på %pris%"
  VinderenBliverFundet: "&8[ &e&lCOIN&f&lFLIP &8] &7Vinderen bliver fundet om &e&l%tid%"
  HarTagetDitCoinflip: "&8[ &e&lCOIN&f&lFLIP &8] &f%player%&7 har taget dit coinflip"
  DuFlipperimod: "&8[ &e&lCOIN&f&lFLIP &8] &7Du flipper imod &f%flipper%"
  Over0: "&8[ &e&lCOIN&f&lFLIP &8] &cDet skal være et tal over 0"
  regexMatcherikke: "&8[ &e&lCOIN&f&lFLIP &8] &7Du skal skrive et &ctal"
  Oprettet: "&8[ &e&lCOIN&f&lFLIP &8] &fDu har oprettet et coinflip på &a&l%num%"
  ikkenogenigang: "&8[ &e&lCOIN&f&lFLIP &8] &fDu har ikke nogen coinflip igang.
  "
  Etigang:
    - "&8[ &e&lCOIN&f&lFLIP &8] &cDu kan kun have 1 coinflip igang"
    - "&8[ &e&lCOIN&f&lFLIP &8] &f/coinflip &cfjern"


Reload:
  permission: coinflip.admin